// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAutoClaimStatus():Promise<main.AutoClaimStatusResponse>;

export function GetTaskLabels(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetUserInfo(arg1:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function StartAutoClaiming(arg1:main.AutoClaimConfig):Promise<main.AutoClaimResponse>;

export function StopAutoClaiming():Promise<main.AutoClaimResponse>;
