// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoClaimStatus() {
  return window['go']['main']['App']['GetAutoClaimStatus']();
}

export function GetTaskLabels(arg1, arg2) {
  return window['go']['main']['App']['GetTaskLabels'](arg1, arg2);
}

export function GetUserInfo(arg1) {
  return window['go']['main']['App']['GetUserInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartAutoClaiming(arg1) {
  return window['go']['main']['App']['StartAutoClaiming'](arg1);
}

export function StopAutoClaiming() {
  return window['go']['main']['App']['StopAutoClaiming']();
}
